### ISSUE TITLE
MPI mesh decomposition does not work with arbitrary cell numbers

### ISSUE THREAD

**Issue by marcfehling** [FireDynamics/fdsgeogen#1]
Dear fdsgeogen community,

the decomposition parameter does not work with arbitrary cell numbers, see the following example:
[minimal_example.xml.zip](https://github.com/FireDynamics/fdsgeogen/files/1230334/minimal_example.xml.zip)

My suggestion would be to add the leftover cells to the last mesh, like a modulo.

Best, Marc

**Comment by lu-kas** [comment]
Just give it a try!
